/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketLookupRouteImport } from './routes/ticket-lookup'
import { Route as ManualScanRouteImport } from './routes/manual-scan'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AgentLogsRouteImport } from './routes/agent-logs'
import { Route as IndexRouteImport } from './routes/index'

const TicketLookupRoute = TicketLookupRouteImport.update({
  id: '/ticket-lookup',
  path: '/ticket-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualScanRoute = ManualScanRouteImport.update({
  id: '/manual-scan',
  path: '/manual-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLogsRoute = AgentLogsRouteImport.update({
  id: '/agent-logs',
  path: '/agent-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-logs': typeof AgentLogsRoute
  '/history': typeof HistoryRoute
  '/manual-scan': typeof ManualScanRoute
  '/ticket-lookup': typeof TicketLookupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-logs': typeof AgentLogsRoute
  '/history': typeof HistoryRoute
  '/manual-scan': typeof ManualScanRoute
  '/ticket-lookup': typeof TicketLookupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-logs': typeof AgentLogsRoute
  '/history': typeof HistoryRoute
  '/manual-scan': typeof ManualScanRoute
  '/ticket-lookup': typeof TicketLookupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-logs'
    | '/history'
    | '/manual-scan'
    | '/ticket-lookup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-logs' | '/history' | '/manual-scan' | '/ticket-lookup'
  id:
    | '__root__'
    | '/'
    | '/agent-logs'
    | '/history'
    | '/manual-scan'
    | '/ticket-lookup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentLogsRoute: typeof AgentLogsRoute
  HistoryRoute: typeof HistoryRoute
  ManualScanRoute: typeof ManualScanRoute
  TicketLookupRoute: typeof TicketLookupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ticket-lookup': {
      id: '/ticket-lookup'
      path: '/ticket-lookup'
      fullPath: '/ticket-lookup'
      preLoaderRoute: typeof TicketLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual-scan': {
      id: '/manual-scan'
      path: '/manual-scan'
      fullPath: '/manual-scan'
      preLoaderRoute: typeof ManualScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-logs': {
      id: '/agent-logs'
      path: '/agent-logs'
      fullPath: '/agent-logs'
      preLoaderRoute: typeof AgentLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentLogsRoute: AgentLogsRoute,
  HistoryRoute: HistoryRoute,
  ManualScanRoute: ManualScanRoute,
  TicketLookupRoute: TicketLookupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
