// <auto-generated />
using System;
using EventTicketingAiPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventTicketingAiPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventTicketingDbContext))]
    [Migration("20260426214434_AddAgentDecisionLogs")]
    partial class AddAgentDecisionLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventTicketingAiPlatform.Application.Domain.Entities.AgentDecisionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("actions");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<bool>("RequiresHumanReview")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_human_review");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_level");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<Guid>("ScanAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_attempt_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ScanAttemptId");

                    b.HasIndex("Severity");

                    b.ToTable("agent_decision_logs", (string)null);
                });

            modelBuilder.Entity("EventTicketingAiPlatform.Application.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.HasKey("Id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EventTicketingAiPlatform.Application.Domain.Entities.ScanAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("GateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gate_id");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_time_ms");

                    b.Property<int>("ReasonCode")
                        .HasColumnType("integer")
                        .HasColumnName("reason_code");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at_utc");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_ip");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ticket_code");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.HasIndex("ScannedAtUtc");

                    b.HasIndex("Source");

                    b.HasIndex("TicketCode");

                    b.HasIndex("TicketCode", "ScannedAtUtc");

                    b.ToTable("scan_attempts", (string)null);
                });

            modelBuilder.Entity("EventTicketingAiPlatform.Application.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ticket_code");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from_utc");

                    b.Property<DateTime>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until_utc");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.ToTable("tickets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
